name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC_USERNAME }}
          key: ${{ secrets.EC_SSH_KEY }}
          script: |
            # Update package list and install necessary packages
            sudo apt update
            sudo apt install -y python3-venv python3-dev build-essential libssl-dev libffi-dev python3-setuptools pkg-config libmysqlclient-dev

            # Remove previous virtual environment and deployment directory
            rm -rf myenv2
            rm -rf postdjdeploy2
            sudo killall python || true

            # Create a new deployment directory and navigate into it
            mkdir postdjdeploy2
            cd postdjdeploy2

            # Initialize a new git repository and pull the latest code
            git init
            git pull https://github.com/Gajanan-kale/Chatbot_naive_bert_250524.git main

            # Create and activate a new virtual environment
            python3 -m venv myenv2
            source myenv2/bin/activate

            # Upgrade pip to the latest version
            pip install --upgrade pip
            pip install django
            # Install Python dependencies
            pip install -r requirements.txt

            # Run Django database migrations
            python3 manage.py migrate

            # Run the Django development server
            nohup python3 manage.py runserver 0.0.0.0:8000 &
            
            # Optionally, collect static files if needed
            # python3 manage.py collectstatic --noinput

            # Optionally, restart your application server (e.g., Gunicorn, uWSGI, etc.)
            # sudo systemctl restart gunicorn
