name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC_USERNAME }}
          key: ${{ secrets.EC_SSH_KEY }}
          script: |
            # Change to your project directory on the EC2 instance
            #sudo apt update

            rm -rf myenv2
            rm -rf postdjdeploy2
            sudo killall python

            mkdir postdjdeploy2
            cd postdjdeploy2
            #virtualenv myenv2
            
            git init 
            #git branch -m main
            git remote add origin git@github.com:Gajanan-kale/Chatbot_naive_bert_250524.git
            # Pull the latest code from the Git repository
            git pull orign main
            git pull https://github.com/Gajanan-kale/Chatbot_naive_bert_250524.git main
            python3 -m venv myenv2

            # Activate your virtual environment
            source myenv2/bin/activate
            #source myenv/bin/activate

            # Install or update Python dependencies
            #pip install -r requirements.txt

            
            # Run Django database migrations
      
            python3 manage.py migrate 
            python3 manage.py runserver 0.0.0.0:8000
            #python manage.py migrate

            # Run Django database migrations
      
            #python3 manage.py migrate 
            #python3 manage.py runserver 0.0.0.0:8006

            # Collect static files (if you're serving them via Django)
            #python manage.py collectstatic --noinput

            # Restart your application server (e.g., Gunicorn, uWSGI, etc.)
            #systemctl restart gunicorn

